[package]
name = "athena-web-core"
version.workspace = true
description.workspace = true
edition.workspace = true
license-file = "../../../LICENSE"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
athena-application = { path = "../application" }
athena-domain = { path = "../domain" }
athena-editor = { path = "../editor" }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
uuid.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.77"
