; Athena Tree-sitter highlight queries — SYNTAX UX ONLY (AD-107).
; Never used for semantic diagnostics or Engineering IR.

(system_declaration "system" @athenaDeclarationKeyword)
(package_declaration "package" @athenaDeclarationKeyword)
(import_declaration "import" @athenaDeclarationKeyword)
(incomplete_package_declaration "package" @athenaDeclarationKeyword)
(incomplete_import_declaration "import" @athenaDeclarationKeyword)
(device_declaration "device" @athenaDeclarationKeyword)
(port_declaration "port" @athenaDeclarationKeyword)
(nested_port_declaration "port" @athenaDeclarationKeyword)
(function_declaration "function" @athenaFunctionKeyword)
(function_role "role" @athenaFunctionKeyword)
(function_ports "ports" @athenaFunctionKeyword)
(connect_declaration "connect" @athenaRelationshipKeyword)
(connect_declaration "->" @operator)
(connect_group_edge "->" @operator)
(layout_declaration "layout" @athenaLayoutKeyword)
(place_statement "place" @athenaLayoutKeyword)
(fixed_place_statement "place" @athenaLayoutKeyword)
(fixed_place_statement "at" @athenaLayoutKeyword)
(fixed_place_statement "orientation" @athenaLayoutKeyword)
(layout_orientation) @athenaLayoutKeyword
(align_statement "align" @athenaLayoutKeyword)
(group_statement "group" @athenaLayoutKeyword)
(layout_placement_relation) @athenaLayoutKeyword
(layout_axis) @athenaLayoutKeyword
(align_statement "aligned-with" @athenaLayoutOperator)
(align_statement "axis" @athenaLayoutKeyword)
(group_statement "grouped-with" @athenaLayoutOperator)
(installation_declaration "installation" @athenaLayoutKeyword)
(installation_declaration "cabinet" @athenaLayoutKeyword)
(installation_enclosure "enclosure" @athenaLayoutKeyword)
(installation_enclosure "size" @athenaLayoutKeyword)
(installation_surface "surface" @athenaLayoutKeyword)
(installation_surface "in" @athenaLayoutKeyword)
(installation_surface "at" @athenaLayoutKeyword)
(installation_surface "size" @athenaLayoutKeyword)
(installation_surface "accepts" @athenaLayoutKeyword)
(installation_rail "rail" @athenaLayoutKeyword)
(installation_rail "on" @athenaLayoutKeyword)
(installation_rail "at" @athenaLayoutKeyword)
(installation_rail "length" @athenaLayoutKeyword)
(installation_rail "orientation" @athenaLayoutKeyword)
(installation_rail "mounting" @athenaLayoutKeyword)
(installation_duct "duct" @athenaLayoutKeyword)
(installation_duct "in" @athenaLayoutKeyword)
(installation_duct "at" @athenaLayoutKeyword)
(installation_duct "size" @athenaLayoutKeyword)
(installation_duct "orientation" @athenaLayoutKeyword)
(installation_duct "wall" @athenaLayoutKeyword)
(installation_channel "channel" @athenaLayoutKeyword)
(installation_channel "in" @athenaLayoutKeyword)
(installation_channel "at" @athenaLayoutKeyword)
(installation_channel "size" @athenaLayoutKeyword)
(installation_channel "lanes" @athenaLayoutKeyword)
(installation_channel "margin" @athenaLayoutKeyword)
(installation_terminal_group "terminal-group" @athenaLayoutKeyword)
(installation_terminal_group "in" @athenaLayoutKeyword)
(installation_terminal_group "at" @athenaLayoutKeyword)
(installation_terminal_group "size" @athenaLayoutKeyword)
(installation_terminal_group "orientation" @athenaLayoutKeyword)
(installation_terminal_group "accepts" @athenaLayoutKeyword)
(installation_mount "mount" @athenaLayoutKeyword)
(installation_mount "device" @athenaLayoutKeyword)
(installation_mount "on" @athenaLayoutKeyword)
(installation_mount "at" @athenaLayoutKeyword)
(installation_mount "orientation" @athenaLayoutKeyword)
(installation_route "route" @athenaLayoutKeyword)
(installation_route "through" @athenaLayoutKeyword)
(length_literal) @number
(symbol_declaration "symbol" @athenaRepresentationKeyword)
(symbol_identity "identity" @athenaRepresentationKeyword)
(symbol_version "version" @athenaRepresentationKeyword)
(element_declaration "element" @athenaRepresentationKeyword)
(element_identity "identity" @athenaRepresentationKeyword)
(element_version "version" @athenaRepresentationKeyword)
(element_bounds "bounds" @athenaPrimitiveKeyword)
(element_child "child" @athenaRepresentationKeyword)
(child_symbol_reference "symbol" @athenaRepresentationKeyword)
(child_translate "translate" @athenaRepresentationKeyword)
(child_rotate "rotate" @athenaRepresentationKeyword)
(child_scale "scale" @athenaRepresentationKeyword)
(child_z_order "zOrder" @athenaRepresentationKeyword)
(element_export_anchor "export" @athenaRepresentationKeyword)
(element_export_anchor "anchor" @athenaRepresentationKeyword)
(element_export_anchor "from" @athenaPrimitiveKeyword)
(element_export_label "export" @athenaRepresentationKeyword)
(element_export_label "label" @athenaPrimitiveKeyword)
(element_export_label "from" @athenaPrimitiveKeyword)
(resource_declaration "resource" @athenaRepresentationKeyword)
(resource_kind "kind" @athenaRepresentationKeyword)
(resource_path "path" @athenaRepresentationKeyword)
(graphic_declaration "graphic" @athenaRepresentationKeyword)
(graphic_declaration "svg" @athenaRepresentationKeyword)
(graphic_declaration "resource" @athenaRepresentationKeyword)
(graphic_bounds "bounds" @athenaPrimitiveKeyword)
(line_primitive "line" @athenaPrimitiveKeyword)
(line_primitive "from" @athenaPrimitiveKeyword)
(line_primitive "to" @athenaPrimitiveKeyword)
(polyline_primitive "polyline" @athenaPrimitiveKeyword)
(polyline_primitive "points" @athenaPrimitiveKeyword)
(arc_primitive "arc" @athenaPrimitiveKeyword)
(arc_primitive "center" @athenaPrimitiveKeyword)
(arc_primitive "radius" @athenaPrimitiveKeyword)
(arc_primitive "from" @athenaPrimitiveKeyword)
(arc_primitive "sweep" @athenaPrimitiveKeyword)
(circle_primitive "circle" @athenaPrimitiveKeyword)
(circle_primitive "center" @athenaPrimitiveKeyword)
(circle_primitive "radius" @athenaPrimitiveKeyword)
(rectangle_primitive "rectangle" @athenaPrimitiveKeyword)
(rectangle_primitive "at" @athenaPrimitiveKeyword)
(rectangle_primitive "size" @athenaPrimitiveKeyword)
(label_slot "label" @athenaPrimitiveKeyword)
(label_slot "at" @athenaPrimitiveKeyword)
(label_slot "size" @athenaPrimitiveKeyword)
(label_slot "role" @athenaPrimitiveKeyword)
(style_reference "style" @athenaPrimitiveKeyword)
(anchor_declaration "anchor" @athenaRepresentationKeyword)
(primitive_reference "primitiveRef" @athenaPrimitiveKeyword)
(anchor_point "point" @athenaPrimitiveKeyword)
(anchor_role "role" @athenaRepresentationKeyword)
(anchor_direction "accepts" @athenaRepresentationKeyword)
(anchor_direction "direction" @athenaPortKeyword)
(anchor_signal "accepts" @athenaRepresentationKeyword)
(anchor_signal "signal" @athenaPortKeyword)
(profile_declaration "profile" @athenaProfileKeyword)
(profile_projection "projection" @athenaProfileKeyword)
(profile_standard "standard" @athenaProfileKeyword)
(profile_style "style" @athenaProfileKeyword)
(profile_fallback "fallback" @athenaProfileKeyword)
(profile_fallback value: (profile_value_name) @athenaProfileKeyword)
(binding_declaration "binding" @athenaBindingKeyword)
(binding_profile "profile" @athenaBindingKeyword)
(binding_priority "priority" @athenaBindingKeyword)
(binding_select "select" @athenaBindingKeyword)
(binding_select (binding_subject_kind) @athenaBindingKeyword)
(binding_select "where" @athenaBindingKeyword)
(binding_use_element "use" @athenaBindingKeyword)
(binding_use_element "element" @athenaBindingKeyword)
(binding_use_element "version" @athenaBindingKeyword)
(binding_variant "variant" @athenaBindingKeyword)

(name) @variable
(view_family_name) @namespace
((property_name) @athenaPortKeyword
  (#match? @athenaPortKeyword "^(direction|signal)$"))
((property_name) @property
  (#not-match? @property "^(direction|signal)$"))
(package_name) @namespace
((identifier) @athenaPortKeyword
  (#match? @athenaPortKeyword "^(in|out)$"))
((identifier) @variable
  (#not-match? @variable "^(in|out)$"))
(direction_name) @athenaPortKeyword
(number) @number
(positive_integer) @number
(string) @string
(string_content) @string
