import * as React from '@theia/core/shared/react';
import { ReactWidget } from '@theia/core/lib/browser/widgets/react-widget';
import { DisposableCollection } from '@theia/core/lib/common/disposable';
import { EditorManager, EditorWidget } from '@theia/editor/lib/browser';
import { AthenaGraphAdapterService } from './athena-graph-adapter-service';
import { type AthenaGraphCommandIntentPayload } from './athena-graph-command-intent-protocol';
import { AthenaGraphViewportSize, AthenaGraphViewportTransform, buildAthenaGraphWorkbenchModel } from './athena-graph-workbench-model';
import { AthenaRepositorySessionService } from './athena-repository-session-service';
import { type AthenaActiveSemanticSelection } from './athena-semantic-selection-model';
import { AthenaSemanticSelectionService } from './athena-semantic-selection-service';
import { AthenaGraphNodeDragState, AthenaGraphPanState, AthenaGraphPortConnectSource } from './athena-graph-workbench-types';
/** Graph-first Athena workbench surface with a pannable and zoomable renderer viewport. */
export declare class AthenaGraphWorkbenchWidget extends ReactWidget {
    static readonly ID = "athena.graphWorkbench";
    static readonly LABEL = "Graphical View";
    protected readonly editorManager: EditorManager;
    protected readonly repositorySessionService: AthenaRepositorySessionService;
    protected readonly graphAdapterService: AthenaGraphAdapterService;
    protected readonly semanticSelectionService: AthenaSemanticSelectionService;
    protected currentEditorListeners: DisposableCollection;
    protected diagram: Awaited<ReturnType<AthenaGraphAdapterService["requestDiagram"]>>;
    protected errorMessage: string | undefined;
    protected loading: boolean;
    protected switchingView: boolean;
    protected refreshHandle: number | undefined;
    protected viewportElement: HTMLDivElement | undefined;
    protected viewportObserver: ResizeObserver | undefined;
    protected viewportSize: AthenaGraphViewportSize;
    protected viewportTransform: AthenaGraphViewportTransform;
    protected viewportMode: 'auto-fit' | 'manual';
    protected panState: AthenaGraphPanState | undefined;
    protected dragState: AthenaGraphNodeDragState | undefined;
    protected pendingAutoFit: boolean;
    protected overlayPanelExpanded: boolean;
    protected lastGraphCommandIntent: AthenaGraphCommandIntentPayload | undefined;
    protected connectPortsArmed: boolean;
    protected connectPortsSource: AthenaGraphPortConnectSource | undefined;
    protected connectPortsPending: boolean;
    protected revealingSelectionSemanticId: string | undefined;
    protected init(): void;
    protected bindCurrentEditor(widget: EditorWidget | undefined): void;
    protected isAthenaEditor(widget: EditorWidget | undefined): widget is EditorWidget;
    protected scheduleRefresh(): void;
    protected refreshDiagram(): Promise<void>;
    protected render(): React.ReactNode;
    protected abbreviateViewLabel(displayName: string): string;
    protected viewIconClass(viewId: string): string;
    protected viewAriaLabel(view: {
        displayName: string;
        description: string;
    }): string;
    protected connectPortsButtonTitle(): string;
    protected relatedSubjectLabel(relation: 'owner' | 'owned-port' | 'connection' | 'source-port' | 'target-port'): string;
    protected toggleOverlayPanel(): void;
    protected toggleConnectPortsMode(): void;
    protected statusIconClass(statusTone: ReturnType<typeof buildAthenaGraphWorkbenchModel>['statusTone']): string;
    protected buildStageStyle(model: ReturnType<typeof buildAthenaGraphWorkbenchModel>): React.CSSProperties;
    protected bindViewportElement: (element: HTMLDivElement | null) => void;
    protected syncViewportSize(): void;
    protected fitViewportToDiagram(): void;
    protected fitViewportToDiagramIfPossible(): void;
    protected resetZoom(): void;
    protected graphNodeTransform(nodeId: string): string | undefined;
    protected stepZoom(multiplier: number): void;
    protected getViewportCenterPoint(): {
        x: number;
        y: number;
    };
    protected handleViewportClick: (event: React.MouseEvent<HTMLDivElement>) => void;
    protected handleStageClick: (event: React.MouseEvent<HTMLElement>) => void;
    protected handleViewportDoubleClick: (event: React.MouseEvent<HTMLDivElement>) => void;
    protected handleViewportWheel: (event: React.WheelEvent<HTMLDivElement>) => void;
    protected handleViewportPointerDown: (event: React.PointerEvent<HTMLDivElement>) => void;
    protected handleViewportPointerMove: (event: React.PointerEvent<HTMLDivElement>) => void;
    protected handleViewportPointerEnd: (event: React.PointerEvent<HTMLDivElement>) => void;
    protected isInteractiveTarget(target: EventTarget | null): boolean;
    protected handleGraphElementKeyDown(event: React.KeyboardEvent<SVGGElement>, semanticId: string, kind: 'component' | 'label', label: string): Promise<void> | void;
    protected handleNodeClick(event: React.MouseEvent<SVGGElement>, semanticId: string, kind: 'component' | 'label', label: string): Promise<void> | void;
    protected handleNodeSelection(semanticId: string, kind: 'component' | 'label', label: string): Promise<void>;
    protected isConnectablePortNode(semanticId: string, kind: 'component' | 'label'): boolean;
    protected handleConnectablePortSelection(semanticId: string, label: string): Promise<void>;
    protected handleComponentPointerDown(event: React.PointerEvent<SVGGElement>, semanticId: string, x: number, y: number): void;
    protected reconcileTransientSelection(diagram: Awaited<ReturnType<AthenaGraphAdapterService['requestDiagram']>>): void;
    protected switchActiveView(viewId: string): Promise<void>;
    protected submitPlacementIntent(dragState: AthenaGraphNodeDragState): Promise<void>;
    protected submitConnectPortsIntent(sourceSemanticId: string, targetSemanticId: string): Promise<void>;
    protected handleSemanticSelectionChanged(selection: AthenaActiveSemanticSelection | undefined, diagramOverride?: Awaited<ReturnType<AthenaGraphAdapterService['requestDiagram']>>): Promise<void>;
}
//# sourceMappingURL=athena-graph-workbench-widget.d.ts.map