import * as React from '@theia/core/shared/react';
import { ReactWidget } from '@theia/core/lib/browser/widgets/react-widget';
import { DisposableCollection } from '@theia/core/lib/common/disposable';
import { EditorManager, EditorWidget } from '@theia/editor/lib/browser';
import type { AthenaComponentKnowledgeSessionPayload } from './athena-component-knowledge-protocol';
import type { AthenaAuthoringPreviewPayload } from './athena-authoring-protocol';
import { AthenaComponentPanelGroup, AthenaComponentPanelItem } from './athena-component-panel-model';
import { AthenaLspEditorBridgeService } from './athena-lsp-editor-bridge-service';
import { AthenaRepositorySessionService } from './athena-repository-session-service';
import { AthenaSemanticSelectionService } from './athena-semantic-selection-service';
export declare class AthenaComponentPanelWidget extends ReactWidget {
    static readonly ID = "athena.componentPanel";
    static readonly LABEL = "Components";
    protected readonly editorManager: EditorManager;
    protected readonly repositorySessionService: AthenaRepositorySessionService;
    protected readonly lspEditorBridgeService: AthenaLspEditorBridgeService;
    protected readonly semanticSelectionService: AthenaSemanticSelectionService;
    protected currentEditorListeners: DisposableCollection;
    protected knowledge: AthenaComponentKnowledgeSessionPayload | undefined;
    protected groups: AthenaComponentPanelGroup[];
    protected loading: boolean;
    protected errorMessage: string | undefined;
    protected previewMessage: string | undefined;
    protected activePreview: AthenaAuthoringPreviewPayload | undefined;
    protected previewingConceptId: string | undefined;
    protected applyingDecision: boolean;
    protected refreshHandle: number | undefined;
    protected init(): void;
    protected bindCurrentEditor(widget: EditorWidget | undefined): void;
    protected scheduleRefresh(): void;
    protected refreshCatalog(): Promise<void>;
    protected isAthenaEditor(widget: EditorWidget | undefined): widget is EditorWidget;
    protected canPreviewInsert(): boolean;
    protected previewComponentInsertion(item: AthenaComponentPanelItem): Promise<void>;
    protected acceptActivePreview(): Promise<void>;
    protected rejectActivePreview(): Promise<void>;
    protected render(): React.ReactNode;
    protected renderItem(item: AthenaComponentPanelItem): React.ReactNode;
}
//# sourceMappingURL=athena-component-panel-widget.d.ts.map