import readySheet from '../../m19/schematic-sheet-proof/ready-sheet.diagram.mjs';

const readyDiagram = {
    ...readySheet,
    projectName: 'M20DenseSheetProof',
    drawingRules: {
        minimumSpacingPx: 32,
        labelOffsetPx: 18,
        routingLaneStyle: 'orthogonal',
        titleBlockSafeMarginPx: 48,
    },
    sheets: readySheet.sheets.map(currentSheet => ({
        ...currentSheet,
        subjectSemanticIds: [
            'component:PSU1',
            'component:PLC2',
            'component:M1',
            'connection:PSU1.plus->PLC1.power',
            'connection:PSU1.plus->PLC2.power',
            'connection:PLC2.power->M1.in',
            'port:PSU1.plus',
            'port:PLC1.power',
            'port:PLC2.power',
            'port:M1.in',
        ],
        composition: {
            sheetId: currentSheet.sheetId,
            displayName: currentSheet.displayName,
            order: currentSheet.order,
            subjectSemanticIds: [
                'component:PSU1',
                'component:PLC2',
                'component:M1',
                'connection:PSU1.plus->PLC1.power',
                'connection:PSU1.plus->PLC2.power',
                'connection:PLC2.power->M1.in',
                'port:PSU1.plus',
                'port:PLC1.power',
                'port:PLC2.power',
                'port:M1.in',
            ],
            representationFamilyId: 'schematic-sheet',
            publication: {
                pageSize: {
                    format: 'A3',
                    orientation: 'landscape',
                },
                frame: {
                    frameId: 'engineering-sheet-frame',
                    style: 'schematic',
                },
                coordinateZones: [
                    {
                        zoneId: 'header',
                        label: 'Header',
                        order: 0,
                    },
                    {
                        zoneId: 'body',
                        label: 'Body',
                        order: 1,
                    },
                    {
                        zoneId: 'title-block',
                        label: 'Title Block',
                        order: 2,
                    },
                ],
                titleBlock: {
                    sheetTitle: currentSheet.displayName,
                    sheetFamily: 'schematic-sheet',
                    sheetNumber: '01-main',
                },
                revisionMetadata: {
                    revisionNote: 'Dense schematic readability proof',
                    revisionCode: 'A',
                },
                viewComposition: {
                    primaryViewId: 'schematic-sheet',
                    primarySheetOrder: currentSheet.order,
                    subjectSemanticIds: [
                        'component:PSU1',
                        'component:PLC2',
                        'component:M1',
                        'connection:PSU1.plus->PLC1.power',
                        'connection:PSU1.plus->PLC2.power',
                        'connection:PLC2.power->M1.in',
                        'port:PSU1.plus',
                        'port:PLC1.power',
                        'port:PLC2.power',
                        'port:M1.in',
                    ],
                },
            },
        },
    })),
    graph: {
        ...readySheet.graph,
        id: 'M20DenseSheetProof:schematic-sheet',
        canvas: {
            width: 1440,
            height: 960,
        },
        nodes: [
            ...readySheet.graph.nodes,
            {
                id: 'schematic/projection/node/component_PLC2',
                semanticId: 'component:PLC2',
                type: 'node',
                kind: 'component',
                label: 'PLC2',
                position: { x: 540, y: 112 },
                size: { width: 216, height: 160 },
            },
            {
                id: 'schematic/projection/label/port_PLC2_power',
                semanticId: 'port:PLC2.power',
                type: 'node',
                kind: 'label',
                label: 'L+',
                position: { x: 764, y: 180 },
                size: { width: 42, height: 22 },
            },
            {
                id: 'schematic/projection/node/component_M1',
                semanticId: 'component:M1',
                type: 'node',
                kind: 'component',
                label: 'M1',
                position: { x: 900, y: 320 },
                size: { width: 200, height: 144 },
            },
            {
                id: 'schematic/projection/label/port_M1_in',
                semanticId: 'port:M1.in',
                type: 'node',
                kind: 'label',
                label: 'in',
                position: { x: 1116, y: 380 },
                size: { width: 32, height: 22 },
            },
        ],
        edges: [
            ...readySheet.graph.edges,
            {
                id: 'schematic/projection/connection/connection_PSU1_plus_PLC2_power',
                semanticId: 'connection:PSU1.plus->PLC2.power',
                type: 'edge',
                sourcePoint: { x: 360, y: 180 },
                targetPoint: { x: 540, y: 192 },
                routingStyle: 'orthogonal',
                bendPoints: [
                    { x: 456, y: 180 },
                    { x: 456, y: 192 },
                ],
                sourceAnchorId: 'schematic/projection/label/port_PSU1_plus/anchor',
                targetAnchorId: 'schematic/projection/label/port_PLC2_power/anchor',
                sourcePortSemanticId: 'port:PSU1.plus',
                targetPortSemanticId: 'port:PLC2.power',
            },
            {
                id: 'schematic/projection/connection/connection_PLC2_power_M1_in',
                semanticId: 'connection:PLC2.power->M1.in',
                type: 'edge',
                sourcePoint: { x: 540, y: 192 },
                targetPoint: { x: 900, y: 392 },
                routingStyle: 'orthogonal',
                bendPoints: [
                    { x: 708, y: 192 },
                    { x: 708, y: 392 },
                ],
                sourceAnchorId: 'schematic/projection/label/port_PLC2_power/anchor',
                targetAnchorId: 'schematic/projection/label/port_M1_in/anchor',
                sourcePortSemanticId: 'port:PLC2.power',
                targetPortSemanticId: 'port:M1.in',
            },
        ],
    },
};

export default readyDiagram;
