/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 2
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_system = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_device = 5,
  anon_sym_port = 6,
  anon_sym_connect = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_DOT = 9,
  anon_sym_DQUOTE = 10,
  sym_string_content = 11,
  sym_source_file = 12,
  sym_system_declaration = 13,
  sym_declaration = 14,
  sym_device_declaration = 15,
  sym_port_declaration = 16,
  sym_connect_declaration = 17,
  sym_qualified_name = 18,
  sym_property_assignment = 19,
  sym__scalar_value = 20,
  sym_string = 21,
  aux_sym_system_declaration_repeat1 = 22,
  aux_sym_device_declaration_repeat1 = 23,
  aux_sym_qualified_name_repeat1 = 24,
  alias_sym_name = 25,
  alias_sym_property_name = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_system] = "system",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_device] = "device",
  [anon_sym_port] = "port",
  [anon_sym_connect] = "connect",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_source_file] = "source_file",
  [sym_system_declaration] = "system_declaration",
  [sym_declaration] = "declaration",
  [sym_device_declaration] = "device_declaration",
  [sym_port_declaration] = "port_declaration",
  [sym_connect_declaration] = "connect_declaration",
  [sym_qualified_name] = "qualified_name",
  [sym_property_assignment] = "property_assignment",
  [sym__scalar_value] = "_scalar_value",
  [sym_string] = "string",
  [aux_sym_system_declaration_repeat1] = "system_declaration_repeat1",
  [aux_sym_device_declaration_repeat1] = "device_declaration_repeat1",
  [aux_sym_qualified_name_repeat1] = "qualified_name_repeat1",
  [alias_sym_name] = "name",
  [alias_sym_property_name] = "property_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_system] = anon_sym_system,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_device] = anon_sym_device,
  [anon_sym_port] = anon_sym_port,
  [anon_sym_connect] = anon_sym_connect,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_source_file] = sym_source_file,
  [sym_system_declaration] = sym_system_declaration,
  [sym_declaration] = sym_declaration,
  [sym_device_declaration] = sym_device_declaration,
  [sym_port_declaration] = sym_port_declaration,
  [sym_connect_declaration] = sym_connect_declaration,
  [sym_qualified_name] = sym_qualified_name,
  [sym_property_assignment] = sym_property_assignment,
  [sym__scalar_value] = sym__scalar_value,
  [sym_string] = sym_string,
  [aux_sym_system_declaration_repeat1] = aux_sym_system_declaration_repeat1,
  [aux_sym_device_declaration_repeat1] = aux_sym_device_declaration_repeat1,
  [aux_sym_qualified_name_repeat1] = aux_sym_qualified_name_repeat1,
  [alias_sym_name] = alias_sym_name,
  [alias_sym_property_name] = alias_sym_property_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_system] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_device] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_port] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_connect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_system_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_device_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_port_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_connect_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name] = {
    .visible = true,
    .named = true,
  },
  [sym_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar_value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_system_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_device_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_property_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_from = 1,
  field_name = 2,
  field_to = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_from] = "from",
  [field_name] = "name",
  [field_to] = "to",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_from, 1},
    {field_to, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_name,
  },
  [3] = {
    [0] = alias_sym_property_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '}') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'v') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_port);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_device);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_system);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_connect);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_system] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_device] = ACTIONS(1),
    [anon_sym_port] = ACTIONS(1),
    [anon_sym_connect] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_system_declaration] = STATE(29),
    [anon_sym_system] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_device,
    ACTIONS(11), 1,
      anon_sym_port,
    ACTIONS(13), 1,
      anon_sym_connect,
    STATE(3), 2,
      sym_declaration,
      aux_sym_system_declaration_repeat1,
    STATE(17), 3,
      sym_device_declaration,
      sym_port_declaration,
      sym_connect_declaration,
  [25] = 7,
    ACTIONS(9), 1,
      anon_sym_device,
    ACTIONS(11), 1,
      anon_sym_port,
    ACTIONS(13), 1,
      anon_sym_connect,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_declaration,
      aux_sym_system_declaration_repeat1,
    STATE(17), 3,
      sym_device_declaration,
      sym_port_declaration,
      sym_connect_declaration,
  [50] = 6,
    ACTIONS(21), 1,
      anon_sym_device,
    ACTIONS(24), 1,
      anon_sym_port,
    ACTIONS(27), 1,
      anon_sym_connect,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_declaration,
      aux_sym_system_declaration_repeat1,
    STATE(17), 3,
      sym_device_declaration,
      sym_port_declaration,
      sym_connect_declaration,
  [73] = 3,
    ACTIONS(32), 1,
      anon_sym_DOT,
    STATE(6), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(30), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
  [89] = 3,
    ACTIONS(32), 1,
      anon_sym_DOT,
    STATE(7), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(34), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
  [105] = 3,
    ACTIONS(38), 1,
      anon_sym_DOT,
    STATE(7), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(36), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
  [121] = 4,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
    ACTIONS(46), 3,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [138] = 5,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(13), 2,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
    ACTIONS(55), 3,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [157] = 5,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(11), 2,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
    ACTIONS(62), 3,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [176] = 5,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
    ACTIONS(69), 3,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [195] = 1,
    ACTIONS(36), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
      anon_sym_DOT,
  [206] = 5,
    ACTIONS(50), 1,
      sym_identifier,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
    ACTIONS(76), 3,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [225] = 2,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(80), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      sym_identifier,
  [236] = 2,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(84), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      sym_identifier,
  [247] = 2,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(88), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      sym_identifier,
  [258] = 1,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [266] = 1,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [274] = 1,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [282] = 1,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [290] = 1,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [298] = 1,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
  [306] = 3,
    ACTIONS(98), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    STATE(14), 2,
      sym__scalar_value,
      sym_string,
  [317] = 2,
    ACTIONS(102), 1,
      sym_identifier,
    STATE(30), 1,
      sym_qualified_name,
  [324] = 2,
    ACTIONS(102), 1,
      sym_identifier,
    STATE(32), 1,
      sym_qualified_name,
  [331] = 2,
    ACTIONS(102), 1,
      sym_identifier,
    STATE(20), 1,
      sym_qualified_name,
  [338] = 2,
    ACTIONS(104), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      sym_string_content,
  [345] = 1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [349] = 1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
  [353] = 1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
  [357] = 1,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
  [361] = 1,
    ACTIONS(116), 1,
      anon_sym_DASH_GT,
  [365] = 1,
    ACTIONS(118), 1,
      anon_sym_LBRACE,
  [369] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [373] = 1,
    ACTIONS(122), 1,
      sym_identifier,
  [377] = 1,
    ACTIONS(124), 1,
      sym_identifier,
  [381] = 1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
  [385] = 1,
    ACTIONS(126), 1,
      sym_identifier,
  [389] = 1,
    ACTIONS(128), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 89,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 121,
  [SMALL_STATE(9)] = 138,
  [SMALL_STATE(10)] = 157,
  [SMALL_STATE(11)] = 176,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 206,
  [SMALL_STATE(14)] = 225,
  [SMALL_STATE(15)] = 236,
  [SMALL_STATE(16)] = 247,
  [SMALL_STATE(17)] = 258,
  [SMALL_STATE(18)] = 266,
  [SMALL_STATE(19)] = 274,
  [SMALL_STATE(20)] = 282,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 298,
  [SMALL_STATE(23)] = 306,
  [SMALL_STATE(24)] = 317,
  [SMALL_STATE(25)] = 324,
  [SMALL_STATE(26)] = 331,
  [SMALL_STATE(27)] = 338,
  [SMALL_STATE(28)] = 345,
  [SMALL_STATE(29)] = 349,
  [SMALL_STATE(30)] = 353,
  [SMALL_STATE(31)] = 357,
  [SMALL_STATE(32)] = 361,
  [SMALL_STATE(33)] = 365,
  [SMALL_STATE(34)] = 369,
  [SMALL_STATE(35)] = 373,
  [SMALL_STATE(36)] = 377,
  [SMALL_STATE(37)] = 381,
  [SMALL_STATE(38)] = 385,
  [SMALL_STATE(39)] = 389,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_declaration, 3, 0, 1),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_declaration, 4, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_declaration, 3, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_device_declaration, 3, 0, 1), SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_device_declaration, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 3, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_port_declaration, 3, 0, 0), SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 4, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_port_declaration, 4, 0, 0), SHIFT(22),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_declaration, 4, 0, 1),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_device_declaration, 4, 0, 1), SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_device_declaration, 4, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_assignment, 2, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_assignment, 2, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_declaration, 4, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_declaration, 5, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [108] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_declaration, 5, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_athena(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "athena",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
