/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 2
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_package = 2,
  anon_sym_import = 3,
  sym_package_name = 4,
  sym__header_space = 5,
  anon_sym_system = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_device = 9,
  anon_sym_port = 10,
  anon_sym_connect = 11,
  anon_sym_DASH_GT = 12,
  anon_sym_layout = 13,
  sym_view_family_name = 14,
  anon_sym_place = 15,
  anon_sym_near = 16,
  anon_sym_below = 17,
  anon_sym_align = 18,
  anon_sym_aligned_DASHwith = 19,
  anon_sym_axis = 20,
  anon_sym_horizontal = 21,
  anon_sym_vertical = 22,
  anon_sym_group = 23,
  anon_sym_grouped_DASHwith = 24,
  anon_sym_DOT = 25,
  anon_sym_DQUOTE = 26,
  sym_string_content = 27,
  sym_source_file = 28,
  sym_package_declaration = 29,
  sym_import_declaration = 30,
  sym_incomplete_package_declaration = 31,
  sym_incomplete_import_declaration = 32,
  sym_system_declaration = 33,
  sym_declaration = 34,
  sym_device_declaration = 35,
  sym__device_member = 36,
  sym_nested_port_declaration = 37,
  sym_port_declaration = 38,
  sym_connect_declaration = 39,
  sym_connect_group_edge = 40,
  sym_layout_declaration = 41,
  sym_layout_statement = 42,
  sym_place_statement = 43,
  sym_layout_placement_relation = 44,
  sym_align_statement = 45,
  sym_layout_axis = 46,
  sym_group_statement = 47,
  sym_qualified_name = 48,
  sym_property_assignment = 49,
  sym__scalar_value = 50,
  sym_string = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_system_declaration_repeat1 = 53,
  aux_sym_device_declaration_repeat1 = 54,
  aux_sym_nested_port_declaration_repeat1 = 55,
  aux_sym_connect_declaration_repeat1 = 56,
  aux_sym_layout_declaration_repeat1 = 57,
  aux_sym_qualified_name_repeat1 = 58,
  alias_sym_name = 59,
  alias_sym_property_name = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_package] = "package",
  [anon_sym_import] = "import",
  [sym_package_name] = "package_name",
  [sym__header_space] = "_header_space",
  [anon_sym_system] = "system",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_device] = "device",
  [anon_sym_port] = "port",
  [anon_sym_connect] = "connect",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_layout] = "layout",
  [sym_view_family_name] = "view_family_name",
  [anon_sym_place] = "place",
  [anon_sym_near] = "near",
  [anon_sym_below] = "below",
  [anon_sym_align] = "align",
  [anon_sym_aligned_DASHwith] = "aligned-with",
  [anon_sym_axis] = "axis",
  [anon_sym_horizontal] = "horizontal",
  [anon_sym_vertical] = "vertical",
  [anon_sym_group] = "group",
  [anon_sym_grouped_DASHwith] = "grouped-with",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_source_file] = "source_file",
  [sym_package_declaration] = "package_declaration",
  [sym_import_declaration] = "import_declaration",
  [sym_incomplete_package_declaration] = "incomplete_package_declaration",
  [sym_incomplete_import_declaration] = "incomplete_import_declaration",
  [sym_system_declaration] = "system_declaration",
  [sym_declaration] = "declaration",
  [sym_device_declaration] = "device_declaration",
  [sym__device_member] = "_device_member",
  [sym_nested_port_declaration] = "nested_port_declaration",
  [sym_port_declaration] = "port_declaration",
  [sym_connect_declaration] = "connect_declaration",
  [sym_connect_group_edge] = "connect_group_edge",
  [sym_layout_declaration] = "layout_declaration",
  [sym_layout_statement] = "layout_statement",
  [sym_place_statement] = "place_statement",
  [sym_layout_placement_relation] = "layout_placement_relation",
  [sym_align_statement] = "align_statement",
  [sym_layout_axis] = "layout_axis",
  [sym_group_statement] = "group_statement",
  [sym_qualified_name] = "qualified_name",
  [sym_property_assignment] = "property_assignment",
  [sym__scalar_value] = "_scalar_value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_system_declaration_repeat1] = "system_declaration_repeat1",
  [aux_sym_device_declaration_repeat1] = "device_declaration_repeat1",
  [aux_sym_nested_port_declaration_repeat1] = "nested_port_declaration_repeat1",
  [aux_sym_connect_declaration_repeat1] = "connect_declaration_repeat1",
  [aux_sym_layout_declaration_repeat1] = "layout_declaration_repeat1",
  [aux_sym_qualified_name_repeat1] = "qualified_name_repeat1",
  [alias_sym_name] = "name",
  [alias_sym_property_name] = "property_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_import] = anon_sym_import,
  [sym_package_name] = sym_package_name,
  [sym__header_space] = sym__header_space,
  [anon_sym_system] = anon_sym_system,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_device] = anon_sym_device,
  [anon_sym_port] = anon_sym_port,
  [anon_sym_connect] = anon_sym_connect,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_layout] = anon_sym_layout,
  [sym_view_family_name] = sym_view_family_name,
  [anon_sym_place] = anon_sym_place,
  [anon_sym_near] = anon_sym_near,
  [anon_sym_below] = anon_sym_below,
  [anon_sym_align] = anon_sym_align,
  [anon_sym_aligned_DASHwith] = anon_sym_aligned_DASHwith,
  [anon_sym_axis] = anon_sym_axis,
  [anon_sym_horizontal] = anon_sym_horizontal,
  [anon_sym_vertical] = anon_sym_vertical,
  [anon_sym_group] = anon_sym_group,
  [anon_sym_grouped_DASHwith] = anon_sym_grouped_DASHwith,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_source_file] = sym_source_file,
  [sym_package_declaration] = sym_package_declaration,
  [sym_import_declaration] = sym_import_declaration,
  [sym_incomplete_package_declaration] = sym_incomplete_package_declaration,
  [sym_incomplete_import_declaration] = sym_incomplete_import_declaration,
  [sym_system_declaration] = sym_system_declaration,
  [sym_declaration] = sym_declaration,
  [sym_device_declaration] = sym_device_declaration,
  [sym__device_member] = sym__device_member,
  [sym_nested_port_declaration] = sym_nested_port_declaration,
  [sym_port_declaration] = sym_port_declaration,
  [sym_connect_declaration] = sym_connect_declaration,
  [sym_connect_group_edge] = sym_connect_group_edge,
  [sym_layout_declaration] = sym_layout_declaration,
  [sym_layout_statement] = sym_layout_statement,
  [sym_place_statement] = sym_place_statement,
  [sym_layout_placement_relation] = sym_layout_placement_relation,
  [sym_align_statement] = sym_align_statement,
  [sym_layout_axis] = sym_layout_axis,
  [sym_group_statement] = sym_group_statement,
  [sym_qualified_name] = sym_qualified_name,
  [sym_property_assignment] = sym_property_assignment,
  [sym__scalar_value] = sym__scalar_value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_system_declaration_repeat1] = aux_sym_system_declaration_repeat1,
  [aux_sym_device_declaration_repeat1] = aux_sym_device_declaration_repeat1,
  [aux_sym_nested_port_declaration_repeat1] = aux_sym_nested_port_declaration_repeat1,
  [aux_sym_connect_declaration_repeat1] = aux_sym_connect_declaration_repeat1,
  [aux_sym_layout_declaration_repeat1] = aux_sym_layout_declaration_repeat1,
  [aux_sym_qualified_name_repeat1] = aux_sym_qualified_name_repeat1,
  [alias_sym_name] = alias_sym_name,
  [alias_sym_property_name] = alias_sym_property_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [sym_package_name] = {
    .visible = true,
    .named = true,
  },
  [sym__header_space] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_system] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_device] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_port] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_connect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_layout] = {
    .visible = true,
    .named = false,
  },
  [sym_view_family_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_place] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_near] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_below] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_align] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_aligned_DASHwith] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_axis] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_horizontal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vertical] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_group] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_grouped_DASHwith] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_incomplete_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_incomplete_import_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_system_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_device_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__device_member] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_port_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_port_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_connect_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_connect_group_edge] = {
    .visible = true,
    .named = true,
  },
  [sym_layout_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_layout_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_place_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_layout_placement_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_align_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_layout_axis] = {
    .visible = true,
    .named = true,
  },
  [sym_group_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name] = {
    .visible = true,
    .named = true,
  },
  [sym_property_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar_value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_system_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_device_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_nested_port_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_connect_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_layout_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_property_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_axis = 1,
  field_from = 2,
  field_name = 3,
  field_subject = 4,
  field_target = 5,
  field_to = 6,
  field_view_family = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_axis] = "axis",
  [field_from] = "from",
  [field_name] = "name",
  [field_subject] = "subject",
  [field_target] = "target",
  [field_to] = "to",
  [field_view_family] = "view_family",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_target, 2},
  [2] =
    {field_name, 1},
  [3] =
    {field_from, 1},
    {field_to, 3},
  [5] =
    {field_view_family, 1},
  [6] =
    {field_from, 0},
    {field_to, 2},
  [8] =
    {field_subject, 1},
    {field_target, 3},
  [10] =
    {field_axis, 5},
    {field_subject, 1},
    {field_target, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [1] = alias_sym_name,
  },
  [6] = {
    [0] = alias_sym_property_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 10,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 8,
  [51] = 9,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 13,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '.') ADVANCE(40);
      if (lookahead == '{') ADVANCE(34);
      if (lookahead == '}') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'g') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(2);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(3);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'g') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'w') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'w') ADVANCE(15);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 27:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 29:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_package_name);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__header_space);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_view_family_name);
      if (lookahead == '-') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_aligned_DASHwith);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_grouped_DASHwith);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'g', 5,
        'h', 6,
        'i', 7,
        'l', 8,
        'n', 9,
        'p', 10,
        's', 11,
        'v', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 'x') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'm') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'y') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'v') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'y') ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 38:
      if (lookahead == 'k') ADVANCE(53);
      END_STATE();
    case 39:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_axis);
      END_STATE();
    case 45:
      if (lookahead == 'w') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 47:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'z') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(65);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_near);
      END_STATE();
    case 53:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_port);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_align);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_below);
      END_STATE();
    case 60:
      if (lookahead == 'c') ADVANCE(70);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_group);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 66:
      if (lookahead == 'g') ADVANCE(75);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_place);
      END_STATE();
    case 68:
      if (lookahead == 'm') ADVANCE(76);
      END_STATE();
    case 69:
      if (lookahead == 'c') ADVANCE(77);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_device);
      END_STATE();
    case 72:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_layout);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_system);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_connect);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(83);
      END_STATE();
    case 82:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_vertical);
      END_STATE();
    case 84:
      if (lookahead == 'l') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_horizontal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 26},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 26},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 29},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 28},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 29},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_system] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_device] = ACTIONS(1),
    [anon_sym_port] = ACTIONS(1),
    [anon_sym_connect] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_layout] = ACTIONS(1),
    [anon_sym_place] = ACTIONS(1),
    [anon_sym_near] = ACTIONS(1),
    [anon_sym_below] = ACTIONS(1),
    [anon_sym_align] = ACTIONS(1),
    [anon_sym_axis] = ACTIONS(1),
    [anon_sym_horizontal] = ACTIONS(1),
    [anon_sym_vertical] = ACTIONS(1),
    [anon_sym_group] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(77),
    [sym_package_declaration] = STATE(28),
    [sym_import_declaration] = STATE(29),
    [sym_incomplete_package_declaration] = STATE(28),
    [sym_incomplete_import_declaration] = STATE(29),
    [sym_system_declaration] = STATE(85),
    [aux_sym_source_file_repeat1] = STATE(29),
    [anon_sym_package] = ACTIONS(3),
    [anon_sym_import] = ACTIONS(5),
    [anon_sym_system] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 1,
      anon_sym_device,
    ACTIONS(15), 1,
      anon_sym_port,
    ACTIONS(17), 1,
      anon_sym_connect,
    ACTIONS(19), 1,
      anon_sym_layout,
    STATE(3), 2,
      sym_declaration,
      aux_sym_system_declaration_repeat1,
    STATE(37), 4,
      sym_device_declaration,
      sym_port_declaration,
      sym_connect_declaration,
      sym_layout_declaration,
  [29] = 8,
    ACTIONS(13), 1,
      anon_sym_device,
    ACTIONS(15), 1,
      anon_sym_port,
    ACTIONS(17), 1,
      anon_sym_connect,
    ACTIONS(19), 1,
      anon_sym_layout,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_declaration,
      aux_sym_system_declaration_repeat1,
    STATE(37), 4,
      sym_device_declaration,
      sym_port_declaration,
      sym_connect_declaration,
      sym_layout_declaration,
  [58] = 7,
    ACTIONS(27), 1,
      anon_sym_device,
    ACTIONS(30), 1,
      anon_sym_port,
    ACTIONS(33), 1,
      anon_sym_connect,
    ACTIONS(36), 1,
      anon_sym_layout,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_declaration,
      aux_sym_system_declaration_repeat1,
    STATE(37), 4,
      sym_device_declaration,
      sym_port_declaration,
      sym_connect_declaration,
      sym_layout_declaration,
  [85] = 6,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      anon_sym_port,
    ACTIONS(46), 3,
      anon_sym_device,
      anon_sym_connect,
      anon_sym_layout,
    STATE(6), 4,
      sym__device_member,
      sym_nested_port_declaration,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
  [109] = 6,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(58), 1,
      anon_sym_port,
    ACTIONS(56), 3,
      anon_sym_device,
      anon_sym_connect,
      anon_sym_layout,
    STATE(7), 4,
      sym__device_member,
      sym_nested_port_declaration,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
  [133] = 5,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_port,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(66), 3,
      anon_sym_device,
      anon_sym_connect,
      anon_sym_layout,
    STATE(7), 4,
      sym__device_member,
      sym_nested_port_declaration,
      sym_property_assignment,
      aux_sym_device_declaration_repeat1,
  [155] = 3,
    ACTIONS(73), 1,
      anon_sym_DOT,
    STATE(9), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(71), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
      anon_sym_layout,
  [172] = 3,
    ACTIONS(73), 1,
      anon_sym_DOT,
    STATE(10), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(75), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
      anon_sym_layout,
  [189] = 3,
    ACTIONS(79), 1,
      anon_sym_DOT,
    STATE(10), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
      anon_sym_layout,
  [206] = 5,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(16), 2,
      sym_property_assignment,
      aux_sym_nested_port_declaration_repeat1,
    ACTIONS(87), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [226] = 6,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_place,
    ACTIONS(93), 1,
      anon_sym_align,
    ACTIONS(95), 1,
      anon_sym_group,
    STATE(14), 2,
      sym_layout_statement,
      aux_sym_layout_declaration_repeat1,
    STATE(45), 3,
      sym_place_statement,
      sym_align_statement,
      sym_group_statement,
  [248] = 1,
    ACTIONS(77), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_DASH_GT,
      anon_sym_layout,
      anon_sym_DOT,
  [260] = 6,
    ACTIONS(91), 1,
      anon_sym_place,
    ACTIONS(93), 1,
      anon_sym_align,
    ACTIONS(95), 1,
      anon_sym_group,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(18), 2,
      sym_layout_statement,
      aux_sym_layout_declaration_repeat1,
    STATE(45), 3,
      sym_place_statement,
      sym_align_statement,
      sym_group_statement,
  [282] = 5,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    STATE(19), 2,
      sym_property_assignment,
      aux_sym_nested_port_declaration_repeat1,
    ACTIONS(107), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [302] = 5,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_property_assignment,
      aux_sym_nested_port_declaration_repeat1,
    ACTIONS(114), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [322] = 4,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_property_assignment,
      aux_sym_nested_port_declaration_repeat1,
    ACTIONS(121), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [340] = 6,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 1,
      anon_sym_place,
    ACTIONS(128), 1,
      anon_sym_align,
    ACTIONS(131), 1,
      anon_sym_group,
    STATE(18), 2,
      sym_layout_statement,
      aux_sym_layout_declaration_repeat1,
    STATE(45), 3,
      sym_place_statement,
      sym_align_statement,
      sym_group_statement,
  [362] = 5,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 1,
      sym_identifier,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_property_assignment,
      aux_sym_nested_port_declaration_repeat1,
    ACTIONS(142), 4,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [382] = 2,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(146), 5,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
      sym_identifier,
  [394] = 2,
    ACTIONS(134), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(142), 5,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
      sym_identifier,
  [406] = 2,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(150), 5,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
      sym_identifier,
  [418] = 2,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(154), 5,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
      sym_identifier,
  [430] = 2,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(158), 5,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
      sym_identifier,
  [442] = 1,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [451] = 1,
    ACTIONS(162), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [460] = 4,
    ACTIONS(5), 1,
      anon_sym_import,
    ACTIONS(7), 1,
      anon_sym_system,
    STATE(82), 1,
      sym_system_declaration,
    STATE(39), 3,
      sym_import_declaration,
      sym_incomplete_import_declaration,
      aux_sym_source_file_repeat1,
  [475] = 4,
    ACTIONS(5), 1,
      anon_sym_import,
    ACTIONS(7), 1,
      anon_sym_system,
    STATE(69), 1,
      sym_system_declaration,
    STATE(27), 3,
      sym_import_declaration,
      sym_incomplete_import_declaration,
      aux_sym_source_file_repeat1,
  [490] = 4,
    ACTIONS(5), 1,
      anon_sym_import,
    ACTIONS(7), 1,
      anon_sym_system,
    STATE(69), 1,
      sym_system_declaration,
    STATE(39), 3,
      sym_import_declaration,
      sym_incomplete_import_declaration,
      aux_sym_source_file_repeat1,
  [505] = 1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [514] = 1,
    ACTIONS(51), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [523] = 1,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [532] = 1,
    ACTIONS(166), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [541] = 1,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [550] = 1,
    ACTIONS(170), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [559] = 1,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [568] = 1,
    ACTIONS(174), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_device,
      anon_sym_port,
      anon_sym_connect,
      anon_sym_layout,
  [577] = 4,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_qualified_name,
    STATE(40), 2,
      sym_connect_group_edge,
      aux_sym_connect_declaration_repeat1,
  [591] = 3,
    ACTIONS(180), 1,
      anon_sym_import,
    ACTIONS(183), 1,
      anon_sym_system,
    STATE(39), 3,
      sym_import_declaration,
      sym_incomplete_import_declaration,
      aux_sym_source_file_repeat1,
  [603] = 4,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_qualified_name,
    STATE(41), 2,
      sym_connect_group_edge,
      aux_sym_connect_declaration_repeat1,
  [617] = 4,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_qualified_name,
    STATE(41), 2,
      sym_connect_group_edge,
      aux_sym_connect_declaration_repeat1,
  [631] = 4,
    ACTIONS(71), 1,
      anon_sym_DASH_GT,
    ACTIONS(73), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      aux_sym_qualified_name_repeat1,
  [644] = 3,
    ACTIONS(194), 1,
      sym_identifier,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(20), 2,
      sym__scalar_value,
      sym_string,
  [655] = 3,
    ACTIONS(198), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(77), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [666] = 1,
    ACTIONS(201), 4,
      anon_sym_RBRACE,
      anon_sym_place,
      anon_sym_align,
      anon_sym_group,
  [673] = 1,
    ACTIONS(203), 4,
      anon_sym_RBRACE,
      anon_sym_place,
      anon_sym_align,
      anon_sym_group,
  [680] = 1,
    ACTIONS(205), 4,
      anon_sym_RBRACE,
      anon_sym_place,
      anon_sym_align,
      anon_sym_group,
  [687] = 1,
    ACTIONS(207), 4,
      anon_sym_RBRACE,
      anon_sym_place,
      anon_sym_align,
      anon_sym_group,
  [694] = 1,
    ACTIONS(209), 4,
      anon_sym_RBRACE,
      anon_sym_place,
      anon_sym_align,
      anon_sym_group,
  [701] = 3,
    ACTIONS(211), 1,
      anon_sym_DOT,
    STATE(51), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [712] = 3,
    ACTIONS(211), 1,
      anon_sym_DOT,
    STATE(44), 1,
      aux_sym_qualified_name_repeat1,
    ACTIONS(75), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [723] = 2,
    ACTIONS(215), 1,
      sym__header_space,
    ACTIONS(213), 2,
      anon_sym_import,
      anon_sym_system,
  [731] = 2,
    STATE(46), 1,
      sym_layout_axis,
    ACTIONS(217), 2,
      anon_sym_horizontal,
      anon_sym_vertical,
  [739] = 2,
    STATE(79), 1,
      sym_layout_placement_relation,
    ACTIONS(219), 2,
      anon_sym_near,
      anon_sym_below,
  [747] = 2,
    ACTIONS(223), 1,
      sym__header_space,
    ACTIONS(221), 2,
      anon_sym_import,
      anon_sym_system,
  [755] = 1,
    ACTIONS(77), 3,
      anon_sym_RBRACE,
      anon_sym_DOT,
      sym_identifier,
  [761] = 1,
    ACTIONS(225), 2,
      anon_sym_import,
      anon_sym_system,
  [766] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(25), 1,
      sym_qualified_name,
  [773] = 2,
    ACTIONS(227), 1,
      anon_sym_DQUOTE,
    ACTIONS(229), 1,
      sym_string_content,
  [780] = 1,
    ACTIONS(231), 2,
      anon_sym_import,
      anon_sym_system,
  [785] = 2,
    ACTIONS(233), 1,
      sym_identifier,
    STATE(63), 1,
      sym_qualified_name,
  [792] = 2,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(72), 1,
      sym_qualified_name,
  [799] = 1,
    ACTIONS(235), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [804] = 2,
    ACTIONS(237), 1,
      sym_identifier,
    STATE(88), 1,
      sym_qualified_name,
  [811] = 1,
    ACTIONS(239), 1,
      sym_identifier,
  [815] = 1,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
  [819] = 1,
    ACTIONS(243), 1,
      sym_package_name,
  [823] = 1,
    ACTIONS(245), 1,
      anon_sym_LBRACE,
  [827] = 1,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
  [831] = 1,
    ACTIONS(249), 1,
      anon_sym_aligned_DASHwith,
  [835] = 1,
    ACTIONS(251), 1,
      anon_sym_grouped_DASHwith,
  [839] = 1,
    ACTIONS(253), 1,
      anon_sym_LBRACE,
  [843] = 1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
  [847] = 1,
    ACTIONS(255), 1,
      sym_identifier,
  [851] = 1,
    ACTIONS(257), 1,
      sym_identifier,
  [855] = 1,
    ACTIONS(259), 1,
      anon_sym_DQUOTE,
  [859] = 1,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
  [863] = 1,
    ACTIONS(263), 1,
      sym_identifier,
  [867] = 1,
    ACTIONS(265), 1,
      sym_identifier,
  [871] = 1,
    ACTIONS(267), 1,
      sym_identifier,
  [875] = 1,
    ACTIONS(269), 1,
      sym_identifier,
  [879] = 1,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
  [883] = 1,
    ACTIONS(273), 1,
      sym_view_family_name,
  [887] = 1,
    ACTIONS(275), 1,
      sym_identifier,
  [891] = 1,
    ACTIONS(277), 1,
      ts_builtin_sym_end,
  [895] = 1,
    ACTIONS(279), 1,
      anon_sym_axis,
  [899] = 1,
    ACTIONS(281), 1,
      anon_sym_DASH_GT,
  [903] = 1,
    ACTIONS(283), 1,
      anon_sym_DASH_GT,
  [907] = 1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
  [911] = 1,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
  [915] = 1,
    ACTIONS(289), 1,
      sym_identifier,
  [919] = 1,
    ACTIONS(291), 1,
      sym_identifier,
  [923] = 1,
    ACTIONS(293), 1,
      sym_identifier,
  [927] = 1,
    ACTIONS(295), 1,
      sym_package_name,
  [931] = 1,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
  [935] = 1,
    ACTIONS(299), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 85,
  [SMALL_STATE(6)] = 109,
  [SMALL_STATE(7)] = 133,
  [SMALL_STATE(8)] = 155,
  [SMALL_STATE(9)] = 172,
  [SMALL_STATE(10)] = 189,
  [SMALL_STATE(11)] = 206,
  [SMALL_STATE(12)] = 226,
  [SMALL_STATE(13)] = 248,
  [SMALL_STATE(14)] = 260,
  [SMALL_STATE(15)] = 282,
  [SMALL_STATE(16)] = 302,
  [SMALL_STATE(17)] = 322,
  [SMALL_STATE(18)] = 340,
  [SMALL_STATE(19)] = 362,
  [SMALL_STATE(20)] = 382,
  [SMALL_STATE(21)] = 394,
  [SMALL_STATE(22)] = 406,
  [SMALL_STATE(23)] = 418,
  [SMALL_STATE(24)] = 430,
  [SMALL_STATE(25)] = 442,
  [SMALL_STATE(26)] = 451,
  [SMALL_STATE(27)] = 460,
  [SMALL_STATE(28)] = 475,
  [SMALL_STATE(29)] = 490,
  [SMALL_STATE(30)] = 505,
  [SMALL_STATE(31)] = 514,
  [SMALL_STATE(32)] = 523,
  [SMALL_STATE(33)] = 532,
  [SMALL_STATE(34)] = 541,
  [SMALL_STATE(35)] = 550,
  [SMALL_STATE(36)] = 559,
  [SMALL_STATE(37)] = 568,
  [SMALL_STATE(38)] = 577,
  [SMALL_STATE(39)] = 591,
  [SMALL_STATE(40)] = 603,
  [SMALL_STATE(41)] = 617,
  [SMALL_STATE(42)] = 631,
  [SMALL_STATE(43)] = 644,
  [SMALL_STATE(44)] = 655,
  [SMALL_STATE(45)] = 666,
  [SMALL_STATE(46)] = 673,
  [SMALL_STATE(47)] = 680,
  [SMALL_STATE(48)] = 687,
  [SMALL_STATE(49)] = 694,
  [SMALL_STATE(50)] = 701,
  [SMALL_STATE(51)] = 712,
  [SMALL_STATE(52)] = 723,
  [SMALL_STATE(53)] = 731,
  [SMALL_STATE(54)] = 739,
  [SMALL_STATE(55)] = 747,
  [SMALL_STATE(56)] = 755,
  [SMALL_STATE(57)] = 761,
  [SMALL_STATE(58)] = 766,
  [SMALL_STATE(59)] = 773,
  [SMALL_STATE(60)] = 780,
  [SMALL_STATE(61)] = 785,
  [SMALL_STATE(62)] = 792,
  [SMALL_STATE(63)] = 799,
  [SMALL_STATE(64)] = 804,
  [SMALL_STATE(65)] = 811,
  [SMALL_STATE(66)] = 815,
  [SMALL_STATE(67)] = 819,
  [SMALL_STATE(68)] = 823,
  [SMALL_STATE(69)] = 827,
  [SMALL_STATE(70)] = 831,
  [SMALL_STATE(71)] = 835,
  [SMALL_STATE(72)] = 839,
  [SMALL_STATE(73)] = 843,
  [SMALL_STATE(74)] = 847,
  [SMALL_STATE(75)] = 851,
  [SMALL_STATE(76)] = 855,
  [SMALL_STATE(77)] = 859,
  [SMALL_STATE(78)] = 863,
  [SMALL_STATE(79)] = 867,
  [SMALL_STATE(80)] = 871,
  [SMALL_STATE(81)] = 875,
  [SMALL_STATE(82)] = 879,
  [SMALL_STATE(83)] = 883,
  [SMALL_STATE(84)] = 887,
  [SMALL_STATE(85)] = 891,
  [SMALL_STATE(86)] = 895,
  [SMALL_STATE(87)] = 899,
  [SMALL_STATE(88)] = 903,
  [SMALL_STATE(89)] = 907,
  [SMALL_STATE(90)] = 911,
  [SMALL_STATE(91)] = 915,
  [SMALL_STATE(92)] = 919,
  [SMALL_STATE(93)] = 923,
  [SMALL_STATE(94)] = 927,
  [SMALL_STATE(95)] = 931,
  [SMALL_STATE(96)] = 935,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_declaration, 3, 0, 3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_declaration, 4, 0, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_system_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_declaration, 3, 0, 3),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_device_declaration, 3, 0, 3), SHIFT(31),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_device_declaration, 3, 0, 3),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_device_declaration, 3, 0, 3), SHIFT(75),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_declaration, 4, 0, 3),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_device_declaration, 4, 0, 3), SHIFT(33),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_device_declaration, 4, 0, 3),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_device_declaration, 4, 0, 3), SHIFT(75),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_device_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 3, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_port_declaration, 3, 0, 0), SHIFT(30),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_port_declaration, 3, 0, 3),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_nested_port_declaration, 3, 0, 3), SHIFT(43),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_nested_port_declaration, 3, 0, 3), SHIFT(21),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_port_declaration, 3, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 4, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_port_declaration, 4, 0, 0), SHIFT(35),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 4, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_nested_port_declaration_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_nested_port_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_nested_port_declaration_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_layout_declaration_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_layout_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_layout_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_layout_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_port_declaration, 4, 0, 3),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_nested_port_declaration, 4, 0, 3), SHIFT(43),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_nested_port_declaration, 4, 0, 3), SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_port_declaration, 4, 0, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_assignment, 2, 0, 6),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_assignment, 2, 0, 6),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_port_declaration, 5, 0, 3),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_port_declaration, 5, 0, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_declaration, 4, 0, 4),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_layout_declaration, 4, 0, 5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_declaration, 4, 0, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_device_declaration, 5, 0, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_layout_declaration, 5, 0, 5),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 5, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_declaration, 5, 0, 3),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_connect_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_connect_declaration_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_name_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_layout_statement, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align_statement, 6, 0, 9),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_layout_axis, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_place_statement, 4, 0, 8),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_statement, 4, 0, 8),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_incomplete_import_declaration, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_incomplete_package_declaration, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 3, 0, 1),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_declaration, 3, 0, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_connect_group_edge, 3, 0, 7),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [261] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_layout_placement_relation, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_declaration, 5, 0, 3),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_athena(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "athena",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
